language: ruby
rvm:
- 2.0.0
- 2.1.0
- 2.2.0
- 2.3.0
cache: bundler
bundler_args: "--jobs=3 --retry=3 --without=development"
before_script: bundle exec puppet --version
script:
- bundle exec rake lint
- bundle exec rake validate
- bundle exec rake spec
env:
- PUPPET_VERSION='~> 3.8.0'
- PUPPET_VERSION='~> 4.3.0'
matrix:
  exclude:
  - rvm: 2.2.0
    env: PUPPET_VERSION='~> 3.8.0'
  - rvm: 2.3.0
    env: PUPPET_VERSION='~> 3.8.0'
  include:
  - rvm: default
    sudo: required
    services: docker
    env: BEAKER_set=centos7
    script: bundle exec rake beaker
  - rvm: default
    sudo: required
    services: docker
    env: BEAKER_set=jessie
    script: bundle exec rake beaker
